name: Contract Test

on:
  schedule:
    - cron: '0 0 * * *'

jobs:

  test:
    strategy:
      fail-fast: false
      matrix:
        git: ["git=1:2.*"]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: sudo apt-get update

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: |
        sudo apt-get install ${{ matrix.git }}
        git --version
        unzip conn/fixtures/repo_basic.zip -d conn/fixtures
        go test -v ./conn

